"""initial migration

Revision ID: 4c6faa67f3c2
Revises: 
Create Date: 2025-08-18 23:05:00.760953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6faa67f3c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('business_name', sa.String(length=100), nullable=True),
    sa.Column('business_phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=100), nullable=True),
    sa.Column('quote_type', sa.String(length=20), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=True),
    sa.Column('destination', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_method', sa.String(length=20), nullable=True),
    sa.Column('actual_weight', sa.Float(), nullable=True),
    sa.Column('dim_weight', sa.Float(), nullable=True),
    sa.Column('pieces', sa.Integer(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('zone', sa.String(length=5), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('quote_metadata', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_table('email_quote_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('shipper_name', sa.String(), nullable=True),
    sa.Column('shipper_address', sa.String(), nullable=True),
    sa.Column('shipper_contact', sa.String(), nullable=True),
    sa.Column('shipper_phone', sa.String(), nullable=True),
    sa.Column('consignee_name', sa.String(), nullable=True),
    sa.Column('consignee_address', sa.String(), nullable=True),
    sa.Column('consignee_contact', sa.String(), nullable=True),
    sa.Column('consignee_phone', sa.String(), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('special_instructions', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.quote_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_quote_requests')
    op.drop_table('quotes')
    op.drop_table('users')
    # ### end Alembic commands ###
